
export const carsList = [
  "9F",
  "9F Cabrio",
  "Adder",
  "Akuma",
  "Albany Escalade",
  "Alpha",
  "Alpha-Z1",
  "Annis 350Z",
  "Annis GT-R I",
  "Annis RX-7 (FD)",
  "Annis RX-7 (Veilside Fortune)",
  "Annis Silvia (S15)",
  "Annis Skyline GT-R (R34)",
  "Annis WRX 2004",
  "Annis ZR-350",
  "Apocalypse Deathbike",
  "Apocalypse Impaler",
  "Apocalypse Imperator",
  "Apocalypse Issi",
  "Apocalypse Slamvan",
  "Ardent",
  "Asbo",
  "Asea",
  "Asterope",
  "Autarch",
  "Avarus",
  "BF Injection",
  "BF-400",
  "BMX",
  "Bagger",
  "Baller",
  "Baller LE LWB",
  "Baller SG",
  "Banshee",
  "Banshee 900R",
  "Bati 801",
  "Bati 801RR",
  "Beater Emperor",
  "Beater Mariachi Tornado",
  "Beater Surfer",
  "Beater Tornado",
  "Benefactor-Benz 600SEL (W140)",
  "Benefactor-Benz E420 (W210)",
  "Benefactor-Benz Vito (V447)",
  "Benefactor-MG C63 (W205)",
  "Benefactor-MG C63 Coupe (W205)",
  "Benefactor-MG G63 (G770)",
  "Benefactor-MG GT",
  "Benefactor-MG S63 (W222)",
  "Benefactor-MG SL65 (R230)",
  "Benefactor-MG VT Black Series",
  "Benefactor-Maybach Pullman",
  "Bestia GTS",
  "Bison",
  "Blade",
  "Blazer",
  "Blazer Lifeguard",
  "Blista",
  "Blista Kanjo",
  "Bodhi",
  "Bravado Challenger 2016",
  "Bravado Charger 1969",
  "Bravado Charger SRT",
  "Bravado Ram 1500",
  "Bravado Viper 2008",
  "Brawler",
  "Brioso R/A",
  "Buccaneer",
  "Buffalo",
  "Bullet",
  "Burgerfahrzeug Golf GTI Vision",
  "Buzzard",
  "Calico GTF",
  "Canis Grand Cherokee",
  "Caracara 4x4",
  "Carbon RS",
  "Carbonizzare",
  "Casco",
  "Cavalcade",
  "Cheburek",
  "Cheetah",
  "Cheetah Classic",
  "Chimera",
  "Chino",
  "Cliffhanger",
  "Clique",
  "Cognoscenti",
  "Cognoscenti 55",
  "Cognoscenti Cabrio",
  "Coil Cybertruck",
  "Coil Model S",
  "Coil Model X",
  "Coil Roadster",
  "Comet",
  "Comet S2",
  "Comet SR",
  "Contender",
  "Coquette",
  "Coquette Blackfin",
  "Coquette D10",
  "Couquette Classic",
  "Cruiser",
  "Cuban 800",
  "Cyclone",
  "Cypher",
  "Daemon",
  "Declasse Camaro 2020",
  "Declasse Corvette C7",
  "Declasse Tahoe",
  "Defiler",
  "Deveste Eight",
  "Deviant",
  "Diabolus",
  "Diabolus Custom",
  "Dilettante",
  "Dinghy",
  "Dinghy (2-Seater)",
  "Dinghy (Yacht)",
  "Dinka NSX 2017",
  "Dinka RT-3000",
  "Dodo",
  "Dominator",
  "Dominator ASP",
  "Dominator GTT",
  "Dominator GTX",
  "Dominator PiBwasser",
  "Double-T",
  "Drift Yosemite",
  "Dubsta",
  "Dubsta 6x6",
  "Dubsta SG",
  "Dukes",
  "Duster",
  "ETR-1",
  "Elegy RH8",
  "Elegy Retro Custom",
  "Ellie",
  "Emperor",
  "Emperor LX-570",
  "Emperor RCF",
  "Enduro",
  "Entity XF",
  "Enus Continental GT",
  "Enus Cullinan",
  "Enus Phantom",
  "Enus Spectre",
  "Esskey",
  "Euros",
  "Exemplar",
  "F620",
  "FCR 1000",
  "FCR 1000 Custom",
  "FMJ",
  "FQ 2",
  "Faction",
  "Faggio",
  "Felon",
  "Felon GT",
  "Feltzer",
  "Flash GT",
  "Frogger",
  "Fugitive",
  "Furore GT",
  "Fusilade",
  "Futo",
  "Futo GTX",
  "Future Shock Deathbike",
  "Future Shock Issi",
  "GB200",
  "GP-1",
  "GT 500",
  "Gallivanter Defender",
  "Gallivanter Defender Christmas Edition",
  "Gallivanter Defender Halloween Edition",
  "Gargoyle",
  "Gauntlet",
  "Gauntlet Classic",
  "Gauntlet Hellfire",
  "Gauntlet Redwood",
  "Glendale",
  "Granger",
  "Grotti Italia (F458)",
  "Growler",
  "Hakuchou",
  "Hakuchou Drag",
  "Hermes",
  "Hexer",
  "Hotknife",
  "Howard NX-25",
  "Huntley S",
  "Imorgon",
  "Impaler",
  "Infernus",
  "Infernus Classic",
  "Ingot",
  "Innovation",
  "Issi",
  "Itali GTB",
  "Itali GTB Custom",
  "Itali GTO",
  "JB 700",
  "Jackal",
  "Jester",
  "Jester (Racecar)",
  "Jester Classic",
  "Jester RR",
  "Jetmax",
  "Journey",
  "Jugular",
  "Kamacho",
  "Karin Land Cruiser 200",
  "Karin Mark 2",
  "Karin Supra A80",
  "Karin Tundra 2021",
  "Khamelion",
  "Komoda",
  "Krieger",
  "Lampadati Giulia GTA",
  "Landstalker",
  "Lectro",
  "Luxor",
  "Luxor Deluxe",
  "Lynx",
  "Malard",
  "Mamba",
  "Mammatus",
  "Mammoth HUM EV",
  "Manchez",
  "Marquis",
  "Massacro",
  "Maverick",
  "Microlight",
  "Monowheel",
  "Monroe",
  "Moonbeam",
  "Nebula Turbo",
  "Nemesis",
  "Neon",
  "Nero",
  "Nero Custom",
  "Nightblade",
  "Nightshade",
  "Nimbus",
  "Novak",
  "Obey A6",
  "Obey A8",
  "Obey Q8",
  "Obey R8",
  "Obey RS6",
  "Obey RS7",
  "Obey S8 (D4)",
  "Ocelot Eletre",
  "Ocelot F-Type R",
  "Ocelot Vanquish Zagto SB",
  "Ocelot Victor",
  "Oracle",
  "Osiris",
  "P-45 Nokota",
  "PCJ-600",
  "Panto",
  "Paragon R",
  "Pariah",
  "Patriot",
  "Patriot Stretch",
  "Pegassi Huayra BC",
  "Pegassi Performante (LP640)",
  "Penetrator",
  "Penumbra",
  "Peyote Gasser",
  "Pfister 811",
  "Pfister 918 Spyder",
  "Pfister Panamera",
  "Pfister Taycan",
  "Pheonix",
  "Picador",
  "Prairie",
  "Premier",
  "Previon",
  "Progen 675 LT",
  "RE-7B",
  "Raiden",
  "Rancher XL",
  "Rapid GT",
  "Raptor",
  "Rat Bike",
  "Rat-Loader",
  "Rat-Truck",
  "Reaper",
  "Rebel",
  "Rebla GTS",
  "Regina",
  "Remus",
  "Revolter",
  "Rhapsody",
  "Riata",
  "Rocoto",
  "Ruffian",
  "Ruiner",
  "Rumpo",
  "Ruston",
  "Rusty Rebel",
  "SC-1",
  "Sabre Turbo",
  "Sanchez",
  "Sanctus",
  "Sandking SWB",
  "Sandking XL",
  "Schafter",
  "Schafter LWB",
  "Schafter LWB (Armored)",
  "Schafter V12",
  "Schlagen GT",
  "Schwarzer",
  "SeaShark",
  "Seminole",
  "Sentinel Classic",
  "Sentinel XS",
  "Serrano",
  "Seven-70",
  "Shelby GT500",
  "Shotaro",
  "Slam Van",
  "Slamvan Custom",
  "Sovereign",
  "Sparrow",
  "Specter",
  "Speeder",
  "Squalo",
  "Stafford",
  "Stallion",
  "Stinger",
  "Stinger GT",
  "Stirling GT",
  "Street Blazer",
  "Streiter",
  "Stretch",
  "Stryder",
  "Sultan",
  "Sultan Classic",
  "Sultan RS",
  "Sultan RS Classic",
  "Suntrap",
  "Super Diamond",
  "SuperVolito Carbon",
  "Surano",
  "Surge",
  "Swift Deluxe",
  "Swinger",
  "T-20",
  "Tailgater",
  "Tailgater S",
  "Taipan",
  "Tampa",
  "Tempesta",
  "Tezeract",
  "Thrax",
  "Thrust",
  "Tigon",
  "Torero",
  "Toro",
  "Toros",
  "Tri-Cycles Race Bike",
  "Tropic",
  "Tropos Rallye",
  "Truffade Centodieci",
  "Truffade Chiron",
  "Tulip",
  "Turismo Classic",
  "Turismo R",
  "Tyrant",
  "Tyrus",
  "Ubermacht 760 (LI)",
  "Ubermacht I8",
  "Ubermacht M3 (E46)",
  "Ubermacht M3 (G80)",
  "Ubermacht M4 (G82)",
  "Ubermacht M4 (GTS)",
  "Ubermacht M5 (CS)",
  "Ubermacht M5 (CS) Halloween Edition",
  "Ubermacht M5 (E34)",
  "Ubermacht M5 (E60)",
  "Ubermacht M8 (F91)",
  "Ubermacht X5 (E70)",
  "Ubermacht X5 (G05)",
  "Ubermacht X6-M (E71)",
  "Ubermacht X7 (G07)",
  "V-65 Molotok",
  "V-STR",
  "Vacca",
  "Vader",
  "Vagner",
  "Vamos",
  "Vectre",
  "Velierer",
  "Velum",
  "Vigero",
  "Vindicator",
  "Virgo",
  "Virgo Classic",
  "Viseris",
  "Visione",
  "Volatus",
  "Voltic",
  "Voodoo",
  "Voodoo Custom",
  "Vortex",
  "Warrener",
  "Warrener HKR",
  "Washington",
  "Whippet Race Bike",
  "Windsor",
  "Windsor Drop",
  "Wolfsbane",
  "X80 Proto",
  "XA-21",
  "XLS",
  "XLS (Armored)",
  "Yosemite",
  "Yosemite Rancher",
  "Z-Type",
  "Zentorno",
  "Zion",
  "Zion Cabrio",
  "Zion Classic",
  "Zombie Chopper",
  "Zorrusso"
];
export const clothsList = [
  "ACCESSORY",
  "Abibas Marquee Boost Lows shoes",
  "Abibas Pezy Boost 700 V3 Alvah shoes",
  "Abibas Pezy foam shoes",
  "Abibas Pro Bounce 2019 Lows shoes",
  "Abibas leggings",
  "Abibas pants",
  "Abibas sport pants",
  "Abibas sweatpants",
  "Acic Gel Kayano sneakers.",
  "Aghhhhh",
  "Air Bior pullover sweater",
  "Alastor McQueen Oversized sneakers",
  "BACKPACKS",
  "Backpack from the Cubic Friend paired set skin",
  "Backpack with piggy keychain skin",
  "Balenciaga Track sneakers",
  "Bigness mask",
  "Bior pants",
  "Bonk",
  "Boowomp",
  "Branded Small backpack skin",
  "Bro",
  "Brother eww",
  "Capsule backpack skin",
  "Cartoon tickle",
  "Casual neon helmet",
  "Casual neon pants",
  "Casual neon set",
  "Casual neon shoes",
  "Casual neon torso",
  "Chain bag with spikes skin",
  "Chanel top",
  "Chick",
  "Christmas tree mask",
  "Classic Lui Vui backpack skin",
  "Classic denim shorts",
  "Cloud backpack skin",
  "Cross backpack skin",
  "Cupids crown",
  "Custom Jeans",
  "Cyberpunk greatsword accessory",
  "Daft Punk mask",
  "Directed by",
  "Dress",
  "Duck",
  "Duffel Bag skin",
  "FEMALE",
  "Faaah",
  "Festive whistle",
  "Fire Ring",
  "Fur-lined bunny backpack",
  "Gauard bag with Ladudu skin",
  "Gayardo shoulder bag skin",
  "Gingerbread house backpack skin",
  "Glowing Bomber Set NEW Sample LW",
  "Glowing face scarf mask",
  "Goofy laugh",
  "Grand Chain",
  "Grand RP collection T-shirt",
  "Grand RP collection hoodie",
  "Grand RP collection pants",
  "Grand backpack skin",
  "Ground Mordan 4 Retro Laser 30th shoes",
  "HEADWEAR",
  "HaHaHa set crossbody bag skin",
  "Happy bear shoulder bag skin",
  "Hoodie with Balaclava Cap X Yazzy",
  "I love you",
  "Jason blue mask",
  "Kiss",
  "Kolex watch of type *",
  "LM Playboy T-shirt with luminous print",
  "LM Playboy full set with luminous print",
  "LM Playboy jacket with luminous print",
  "LM Playboy mask with luminous print",
  "LM Playboy pants with luminous print",
  "LM Playboy sweatshirt with luminous print",
  "LUV backpack with wings skin",
  "LV backpack with water prints skin",
  "LV crossbody bag skin",
  "LW Crossbody Bag skin",
  "Large LV crossbody bag skin",
  "Laughter",
  "Leather gothic pants",
  "Lightning Charge",
  "Love costume",
  "Lui Vi T-shirt",
  "Lui Vi desert scarf mask",
  "Lui Vi full set",
  "Lui Vi jacket",
  "Lui Vi pants",
  "Lui Vi sweatshirt",
  "Lui Vi top",
  "Luv Moscnino spiky heart backpack skin",
  "MASKS",
  "Memo Bag Ladudu skin",
  "Mikachu hoodie",
  "Mordan 1 shoes",
  "Mordan 6 shoes",
  "Motosport Waist bag skin",
  "Muci Not Fake hoodie",
  "Muci branded flip-flops",
  "Muci hoodie",
  "Muci hoodie with snake",
  "Muci pants",
  "Muci shorts",
  "Muci sweatshirt",
  "Muci trousers",
  "Munk mask",
  "Mwahahaha",
  "Neon Chrome handbag skin",
  "Neon Pants Set New Sample LW",
  "Nik mask",
  "Niki Groundporce One new collection shoes",
  "Niki Shox shoes",
  "Niki Uptempo shoes",
  "Niki Zoom Freak 1 Multi-Color shoes",
  "Niki new collection hoodie",
  "Niki new collection pants",
  "Niki tech fleece pants",
  "Niki tech top",
  "Niki track suit pants",
  "Niki track suit top",
  "No no no no wait",
  "Off-White Pezy Boost shoes",
  "Off-White luminous Keezy Boost shoes",
  "Off-White sweatshirt",
  "PANTS",
  "Pans sneakers",
  "Pezy Boost shoes",
  "Philip Plein T-shirt",
  "RGB neon shoes",
  "Razer headphones",
  "Romantic",
  "SHOES",
  "SSC Kit Bag skin",
  "Sad sound",
  "Sad violin",
  "Santa Claus mask",
  "Saruko neon mask",
  "Sashmello mask",
  "Satanic Wings",
  "Satanic horns",
  "Scary chicken backpack skin",
  "Shorts Lui Vi",
  "Skeleton cheetah plush backpack skin",
  "Skeleton hits a shield",
  "Small shoulder bag LW skin",
  "Snake around the body accessory",
  "Social Club hoodie",
  "Spring set S23",
  "Ston Islan Classic Sportswear",
  "Suspicious",
  "Suspicious sound",
  "Sweet Sheep fur bag",
  "T-shirt of one-color CAP brand",
  "TOP/HOODIE",
  "TRON full set",
  "TRON helmet",
  "TRON pants",
  "TRON shoes",
  "TRON torso",
  "TV-head mask",
  "The West Pace jacket",
  "Toy sound",
  "Tsum collection T-shirt",
  "UP-Green Sweatshirt",
  "Uwu",
  "Vagabond",
  "Vasio G-Shock watch",
  "Volex watch of type *",
  "WATCH",
  "Watch Me sweater",
  "Wedding dress",
  "Whistle sound",
  "Wide printed football T-shirt",
  "Woooow",
  "Yeah boy",
  "alien with neon eyes mask",
  "anime mask",
  "bandana mask",
  "bandana top",
  "baseball mask",
  "black jacket with yellow trim",
  "bomber jacket with glowing elements",
  "boxing gloves",
  "boxing helmet",
  "branded Molo T-shirt",
  "branded T-shirt",
  "branded insulated hoodie",
  "branded longsleeve",
  "bright hoodie",
  "bright trousers",
  "carnival mask",
  "chain around the body accessory",
  "chain lost treasure neon accessory",
  "clown mask",
  "collection 2022 T-shirt",
  "collection 5 top",
  "corset top",
  "cowgirl hat",
  "cropp collection T-shirt",
  "day dress",
  "deer antler accessory",
  "deer antlers with a red nose accessory",
  "demon mask",
  "denim jacket",
  "desert scarf mask",
  "devil mask",
  "dress",
  "earphones with a heart",
  "emoji mask",
  "evil mask",
  "exotic mask",
  "faution top",
  "flying bear on the shoulder accessory",
  "fox mask",
  "fur coat without a hood",
  "gloves",
  "glowing snow glasses",
  "gorilla mask",
  "half-glowing pants",
  "haliky T-shirt",
  "haliky hoodie",
  "handkerchief mask",
  "hearts Pride glasses",
  "insulated personal pants",
  "jacket with T-shirt",
  "jacket with luminous trim",
  "jeans",
  "jumpsuit",
  "kitsune mask",
  "long brand T-shirt",
  "low dress",
  "luminous Fendi pants",
  "luminous Grand RP trousers",
  "luminous Keezy Boost shoes",
  "luminous T-shirt",
  "luminous dress",
  "luminous head bag mask",
  "luminous jacket with turquoise trim",
  "luminous shoes",
  "luminous trousers",
  "mix collection T-shirt",
  "monkey boss mask",
  "navel piercing accessory",
  "neck scarf accessory",
  "neon pants",
  "neon shoes",
  "new fashionable joggers",
  "owl mask",
  "panama hat",
  "penguin mask",
  "pig mask",
  "pixel glasses",
  "pullover with long sleeve",
  "purge mask",
  "rabbit ears",
  "raccoon mask",
  "raptor mask",
  "rare luminous shoes",
  "raven mask",
  "red sneakers",
  "red stocking mask",
  "reindeer mask",
  "robot human mask",
  "robot mask",
  "rooster mask",
  "samurai mask",
  "scary turtleneck T-shirt",
  "shamanic mask",
  "shiny deer antler headband accessory",
  "short pullover",
  "skeleton king mask",
  "skirt with tights",
  "snowboarders mask",
  "snowflake glasses",
  "snowman mask",
  "sports mask",
  "stealthy mask",
  "stylish suit",
  "summer bra",
  "summer collection T-shirt",
  "summer voyage shorts",
  "tall boots",
  "tied scarf mask",
  "tight mask",
  "toothy mask",
  "top 2 outerwear",
  "top Faution",
  "top with chains",
  "trending shark head hat",
  "trendy jacket",
  "vintage Abibas Olympic Jerseys",
  "winter collection dress",
  "wristband accessory"
];

export const officialLocations = [
  "Vinewood Hills",
  "Rockford Hills",
  "Richman",
  "Sandy Shores",
  "Paleto Bay",
  "Postal",
  "Hospital",
  "Capitol",
  "Fire Station",
  "Auto Fair",
  "Bahama Mamas Bar",
  "Tequi-la-la Bar",
  "FIB",
  "Hotel Spa Bar",
  "Pacific Bluffs Country Club",
  "Diamond Resort Bar (Casino Restaurant)",
  "Vanilla Unicorn Bar",
  "Church",
  "Stock Exchange",
  "Stadium",
  "Chumash",
  "Lifeinvader",
  "Del Perro Pier",
  "Del Perro Beach",
  "Cayo Perico Island",
  "Hotel",
  "Raton Canyon",
  "School",
  "SAHP",
  "Mirror Park"
];

export const unofficialLocations = [
  "airport",
  "autosalon",
  "beach",
  "beach market",
  "city",
  "ghetto",
  "post office",
  "train station",
  "yacht"
];

export const allLocations = [...officialLocations, ...unofficialLocations].sort((a, b) => a.localeCompare(b));

export const familyBusinesses = [
  "Burger shop",
  "Cowshed",
  "Freight train",
  "Plantation",
  "Oil Well"
];

export const generalBusinesses = [
  "Ammunition Store",
  "ATM",
  "Bar",
  "Car wash",
  "Car sharing",
  "Chip tuning",
  "Clothing shop",
  "Electric station",
  "Farm",
  "Flower shop",
  "Fight club",
  "Furniture shop",
  "Gas station",
  "Grand Elite",
  "Hair salon",
  "Jewelry store",
  "Juice shop",
  "Luna park",
  "Parking",
  "Pet Shop",
  "State object",
  "Service station",
  "Tattoo studio",
  "Taxi company",
  "Warehouse",
  "24/7 Store"
];

export const sharesBusinesses = [
  "Taxi fleet shares",
  "Gas station shares",
  "Chip tuning shares",
  "Barber shop shares",
  "Tattoo studio shares",
  "Armory store shares",
  "Bar shares",
  "Car sharing shares"
];
